// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1U-O02UZu8FP1TcKR6c4lvmjatj6xksk',
    appId: '1:518913404786:web:73c23c049601681f95b7eb',
    messagingSenderId: '518913404786',
    projectId: 'meta-asm',
    authDomain: 'meta-asm.firebaseapp.com',
    storageBucket: 'meta-asm.appspot.com',
    measurementId: 'G-8KZF5EX4Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD40Pcb84OJTacrY9qxLLR9iWFuOV9urGg',
    appId: '1:518913404786:android:3bf11314fcb025c495b7eb',
    messagingSenderId: '518913404786',
    projectId: 'meta-asm',
    storageBucket: 'meta-asm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCETsP1GHdxe2_xhHFDWhnQSdrDIDM8o_k',
    appId: '1:518913404786:ios:3e0cabbc390f425b95b7eb',
    messagingSenderId: '518913404786',
    projectId: 'meta-asm',
    storageBucket: 'meta-asm.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCETsP1GHdxe2_xhHFDWhnQSdrDIDM8o_k',
    appId: '1:518913404786:ios:6564ef2786f0ea1c95b7eb',
    messagingSenderId: '518913404786',
    projectId: 'meta-asm',
    storageBucket: 'meta-asm.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
